[project]
name = "sist-operacionais"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.7.0",
    "numpy>=1.24.0",
]
